### ISSUE TITLE
Support default "open in new tab" option for links

### ISSUE THREAD

**Issue by carpenike** [toboshii/hajimari#11]
**Is your feature request related to a problem? Please describe.**
When clicking links on the dashboard they default to opening in the same tab.

**Describe the solution you'd like**
Provide an option that either defaults or provides for a user specified / per object configuration that opens links in a new tab.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by toboshii** [comment]
Added in #44
