### ISSUE TITLE
Updating the Configmap should trigger hajimari to reload it's settings

### ISSUE THREAD

**Issue by onedr0p** [toboshii/hajimari#15]
**Is your feature request related to a problem? Please describe.**

Updating the Configmap in the helm chart doesn't update hajimari until the pod is restarted

**Describe the solution you'd like**

Maybe it's possible to split the ui config from the server config and have the ui config be reloaded on change by hajimari?

**Describe alternatives you've considered**

You can use stakater/reloader to have it bounce the pod when the configmap changes.

**Additional context**

**Comment by toboshii** [comment]
Added in #44
