### ISSUE TITLE
Support URL for icons

### ISSUE THREAD

**Issue by angelnu** [toboshii/hajimari#18]
**Is your feature request related to a problem? Please describe.**
In Homer I am able use custom icons which is handy to have the real app icon

**Describe the solution you'd like**
Custom apps support URLs so if this support could be added to the annotation for ingress apps then any icon might be used.

Extended feature would be to upload icons that could be served by the hajimari web server.

**Describe alternatives you've considered**
For the icons a custom container might be created that has the apps each user has but it is an "advanced" feature to build your own container. It would work for me thought.

**Additional context**

**Comment by toboshii** [comment]
Added in #44
