### ISSUE TITLE
Change Default Search Engine

### ISSUE THREAD

**Issue by crutonjohn** [toboshii/hajimari#21]
Users should be able to determine what search engine to use from their Hajimari start page.

A simple setting to support other search engines. Could be a drop down on the main page, with a config setting the default option..but i'm open to any solution to support:
- DuckDuckGo
- Yahoo
- Bing

I'm really just asking because I dislike using google most of the time :)

**Comment by tobru** [comment]
I'd appreciate it as well if I could choose which search engine is being used, I do not like to use Google.

**Comment by ishioni** [comment]
Also adding Startpage.com as one of the choices

**Comment by MrMarble** [comment]
I know it is not the same as a default config, but you can use a special selector to change the search engine.
 - `/d <text>`: DuckDuckGo.
 - `/i <text>`: Imdb.
 - `/r <text>`: Reddit.
 - `/y <tezt>`: Youtube.

If you don't specify a text, it will open then home page of those sites. Also works for Spotify `/s`.

Here's the code https://github.com/toboshii/hajimari/blob/main/web/static/js/search.js#L30

**Comment by toboshii** [comment]
Added in #44
