### ISSUE TITLE
Error message after k3s update to 1.22.2

### ISSUE THREAD

**Issue by cbirkenbeul** [toboshii/hajimari#22]
**Describe the bug**
After upgrading k3s to 1.22.2 i got the error message
`the server could not find the requested resource (get ingresses.extensions)`

Seems to be a API change.

**Comment by solidDoWant** [comment]
Looks like there was a breaking change with 1.22: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by alonso-m** [comment]
Is there any workaround for this other than downgrading?

**Comment by toboshii** [comment]
> Is there any workaround for this other than downgrading?

Currently, no. There are a few other things in my cluster that were not yet updated to support 1.22 so I haven't had a chance to work on this. I plan on attempting to update my cluster this week and will be able to look into this. Should be a simple fix with just a change to the new ingress API path.
