### ISSUE TITLE
Applications not grouped by namespace

### ISSUE THREAD

**Issue by ankushg** [toboshii/hajimari#23]
**Describe the bug**
Applications aren't grouped by namespace.

**To Reproduce**
1. Install Hajimari
2. Set `defaultEnable` to `true` and configure `namespaceSelector` as `any: true`
3. Configure ingresses for applications in multiple namespaces, without annotating with `hajimari.io/group`
4. Open Hajimari 

**Expected behavior**
Hajimari should be grouping applications by namespace.

Docs for `hajimari.io/group` say to `Use if you want the application to show in a different group than the namespace it is running in`

**Comment by davosian** [comment]
I am experiencing the same behavior. Also, overriding with `hajimari.io/group` has no effect either. If I understand it correctly, this should break up the application section into a group per namespace, correct?

**Comment by toboshii** [comment]
Hey, thanks for the reports! This is really less of a bug and more of a feature that was not fully implemented in the initial release. The original startpage style Hajimari is based on (SUI) didn't have grouping for applications so I didn't bother adding it in the UI.

The main work of the next release (v0.2) is a complete rework of the UI into Svelte components and already includes finishing this feature and making it configurable, for both applications and bookmarks you'll be able to choose if you want them grouped or not.

**Comment by davosian** [comment]
Hey @toboshii this is great news! Thanks for sharing this insight into the next release. Looking forward to it!

**Comment by toboshii** [comment]
Added in #44
