### ISSUE TITLE
add arm based docker image

### ISSUE THREAD

**Issue by abualy** [toboshii/hajimari#30]
**Is your feature request related to a problem? Please describe.**
i cannot run succesffuly the helm chart on my raspberry based k8s cluster, since it fails in pulling the image
**Describe the solution you'd like**
can you please add an arm based docker image

**Describe alternatives you've considered**
i have considered uploading my own arm version, but it seems it is better to have it from the source repository
**Additional context**

**Comment by rgstephens** [comment]
Looks like there is an [arm image](https://github.com/toboshii/hajimari/pkgs/container/hajimari)

**Comment by tyriis** [comment]
works well on raspi4

**Comment by abualy** [comment]
i think that was the issue for me and i did not pay attention, but it is working on my arm v8 
closing this issue
thank you for the reply
