### ISSUE TITLE
Helm chart references old v0.1.0 image tag

### ISSUE THREAD

**Issue by zmingee** [toboshii/hajimari#31]
**Describe the bug**
The Helm chart still references the v0.1.0 image tag, while v0.2.0 is available

**To Reproduce**
1. Add Helm repo
2. Install chart following repo instructions
3. Note that container is running tag v0.1.0

**Expected behavior**
The Helm chart should deploy the latest version (v0.2.0)

**Additional context**
I originally noticed the issue because I'm running k8s v1.22.2 and experienced #22

**Comment by lapwat** [comment]
# Fix

[#](https://github.com/toboshii/hajimari/pull/34)

# Workaround until it gets merged

`helm install hajimari hajimari/hajimari --set image.tag=v0.2.0`

**Comment by toboshii** [comment]
Fixed in #44
