### ISSUE TITLE
Support for Istio VirtualService (or CRD ala Forecastle)

### ISSUE THREAD

**Issue by aodj** [toboshii/hajimari#33]
**Is your feature request related to a problem? Please describe.**
In clusters that use Istio there are generally few, if any Ingress objects. Application end points are instead handled via a VirtualService CRD. A similar issue was presented for Forecastle which they [solved](https://github.com/stakater/Forecastle/issues/73) by adding their own CRD to describe application endpoints.

**Describe the solution you'd like**
Support for discovering application endpoints via non-Ingress objects such as Istio's VirtualService or a custom CRD.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by pl4nty** [comment]
+1, this would also be useful for native [Gateway API](https://gateway-api.sigs.k8s.io/) HTTPRoutes or maybe L4 protocols with a custom handler

**Comment by agrrh** [comment]
Hello there!

Just to let you know, I've made an attempt to implement same CRD approach in #117
