### ISSUE TITLE
Support CRD

### ISSUE THREAD

**Issue by cpoulsen** [toboshii/hajimari#37]
**Is your feature request related to a problem? Please describe.**
Seems like it only works for type: Ingress. It would be nice to add support for Traefiks IngressRoute for instance.

**Describe the solution you'd like**
Some way of configuring CRD ingress

**Describe alternatives you've considered**
Hardcoding the ingresses to the applications list, which seems rather pointless.

**Comment by toboshii** [comment]
Duplicate of #33
