### ISSUE TITLE
docker run success，but can't connect web ui

### ISSUE THREAD

**Issue by xinmans** [toboshii/hajimari#43]
root@unraid:/mnt/user/appdata/hajimari# docker run -d --name=hajimari -v /mnt/user/appdata/hajimari:/config -p 12345:3000 ghcr.io/toboshii/hajimari:v0.2.0
c7a1926825a451ed19dd08d9f21dae43754ae8e745b097f0a27047687e69a19d

root@unraid:/mnt/user/appdata/hajimari# docker logs c7a1926825a4
time="2022-08-29T07:59:07Z" level=info msg="Listening on :3000\n" _source="/build/main.go:69"
time="2022-08-29T07:59:14Z" level=fatal msg="Cannot get kubernetes config: stat /home/hajimari/.kube/config: no such file or directory" _source="kube/client.go:56"

**Comment by toboshii** [comment]
Hi @xinmans, thanks for your issue.

At this point in time Hajimari is Kubernetes specific and will not run without a valid kubeconfig. If your intention is to run it locally in docker but connected to a remote k8s cluster (for development for example) you'll need to mount a valid kubeconfig at `/home/hajimari/.kube/config`.

If you are instead looking for something that can run in docker alone, I'm afraid you'll have to look at some other options like [flame](https://github.com/pawelmalak/flame), [heimdall](https://heimdall.site/), or [dashy](https://github.com/lissy93/dashy).
