### ISSUE TITLE
Create Helm chart

### ISSUE THREAD

**Issue by toboshii** [toboshii/hajimari#5]
**Describe the solution you'd like**
Create Helm chart to deploy to kubernetes. Preferably based on KAH commons.

**Comment by onedr0p** [comment]
Usually the issue is having the helm chart being part of the app repo makes it harder to do releases because you can only bump the chart version on new application updates. Would it be better to deploy the chart under toboshii/charts or on kah?

**Comment by toboshii** [comment]
Yea I'm 100% in agreement with it being separated.

The issue with using my chart repo is I is use it as a dumping ground for dirty hacks and I don't want to give anyone ideas that anything in there is `stable`.

I'm fine with it either being on KAH, or what do you think about just moving this to it's own org?

**Comment by toboshii** [comment]
Ignore that, I setup https://github.com/toboshii/charts if you want to put it there, CI is already in place.
