### ISSUE TITLE
Embed Google icon in Good search box

### ISSUE THREAD

**Issue by onedr0p** [toboshii/hajimari#9]
**Is your feature request related to a problem? Please describe.**

I originally thought this was a filter for the apps, it would be neat to embed a Google icon in the search textbox

E.g.

![image](https://user-images.githubusercontent.com/213795/130107082-2bde9411-288f-4d3c-b54d-8b90d8b0540e.png)

**Comment by npawelek** [comment]
Taking this one thought further, perhaps these can be customizable as well. Adding additional search engines like DuckDuckGo or others.

**Comment by mitsumaui** [comment]
> Taking this one thought further, perhaps these can be customizable as well. Adding additional search engines like DuckDuckGo or others.

+1 for this - even if it's being able to specify a search URL so it can be more flexible.

**Comment by toboshii** [comment]
Added in #44
